### PR TITLE
Re-write in Rust

### PR DESCRIPTION
**Pull request by jewlexx**
# I rewrote the entire Tauricon project in Rust.
## The reasons I did this are as follows:
* It results in a smaller bundle size
* Quicker to download a binary, or even in some cases to build from source, than downloading from npm
* More easily integrated into the existing Rust based Tauri cli
* Major performance improvements over NodeJS as it is compiled to binary, and does not rely on native addons like NodeJS image manipulation does

## Added bendefits: 
* Written in 100% Rust
* `#![forbid(unsafe_code)]`

However, I completely understand if you do not want to merge this PR, as I completely rewrote the codebase, my code probably differs from some of your internal conventions, and it is still somewhat a work in progress. This code has bugs in it I am almost certain (I haven't found any yet though), hence I would understand if this is put on hold for a while or ignored entirely.

Love the Tauri project either way, and will continue to contribute my best efforts to the cause <3

### CODE REVIEW

**Comment by FabianLars** [comment]
Wow, great work! A rewrite in rust was the plan all along, primarily to merge it back into the main cli how it used to be. tauricon was "outsourced" because we changed tauri-cli to 100% rust, but didn't have the time to rewrite tauricon _and_ it all happened after the audit which probably would've blocked it anyway.

And this is also why i won't merge this PR (yet), i'd much rather see this integrated into the main cli after v1. Furthermore, because tauricon is most of the times used only once, `npx tauricon` is much nicer than `cargo install` (irrelevant once it's part of the cli again)

> Love the Tauri project either way, and will continue to contribute my best efforts to the cause <3

We really appreciate it ❤️ That said, next time _i_ wouldd appreciate it if you could file an issue or reach out on discord before really getting to it so we can better align our visions and stuff :P

**Comment by jewlexx** [comment]
> That said, next time i wouldd appreciate it if you could file an issue or reach out on discord before really getting to it so we can better align our visions and stuff :P

Of course. If you want to collaborate on merging into the main cli in future let me know.

Also, I'd love to keep working on this, so if you have any directions, I'd love to chat so we can align our visions.

Finally, I did consider the `npx tauricon` vs `cargo install`, and I found [Neon](https://neon-bindings.com/), which you may have already heard of. I am not 100% sure how Node add-ons work, but I think [Neon](https://neon-bindings.com/) could be a good way of integrating `tauricon` into a NodeJS environment better. [WASI](https://wasi.dev/) is another option for cross platform compilation that is *alot* faster than `cargo install`.

**Comment by nothingismagick** [comment]
This is great, and would actually remove all of the dependency vulnerabilities. Don't know how I missed this great stuff!

**Comment by nothingismagick** [comment]
next step will be to write an run the tests @jewlexx :)

**Pull request closed without merging**
